spring:
  application:
    name: Pathology-Lab-System

  datasource:
    url: jdbc:mysql://localhost:3306/pathologyLab
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true